//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annuity1
    {
        public long Id { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Yly { get; set; }
        public Nullable<decimal> Hly { get; set; }
        public Nullable<decimal> Qly { get; set; }
        public Nullable<decimal> Mly { get; set; }
        public Nullable<long> LICId { get; set; }
        public Nullable<long> PlanID { get; set; }
        public Nullable<System.DateTime> EffDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
