//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColunmMapMaster
    {
        public int CMID { get; set; }
        public Nullable<int> CompID { get; set; }
        public string TblName { get; set; }
        public string TblClmName { get; set; }
        public Nullable<int> TblClmIndex { get; set; }
        public string ExlClmName { get; set; }
        public Nullable<int> ExlClmIndex { get; set; }
        public Nullable<int> MappedBy { get; set; }
        public Nullable<System.DateTime> MappedDate { get; set; }
    }
}
