//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompWiseAllowance
    {
        public int id { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> AllowanceID { get; set; }
        public Nullable<System.DateTime> EffDeate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<int> GradeID { get; set; }
    }
}
