//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMaster
    {
        public int id { get; set; }
        public string CompCode { get; set; }
        public string CompName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public string Type { get; set; }
        public Nullable<int> WidowPension { get; set; }
        public Nullable<int> PensionEligibityYears { get; set; }
        public Nullable<int> Status { get; set; }
        public string PensionLimit { get; set; }
        public string Merging { get; set; }
        public Nullable<int> SAIntMethod { get; set; }
        public Nullable<decimal> SAContriRate { get; set; }
        public Nullable<int> SAStopIntType { get; set; }
        public Nullable<int> SAContriMethod { get; set; }
    }
}
