//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public int EmpId { get; set; }
        public Nullable<int> CompId { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<int> RetireTypeId { get; set; }
        public Nullable<System.DateTime> RetireDate { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> FHStatus { get; set; }
        public string FHName { get; set; }
        public string Relation { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string ContactO { get; set; }
        public string ContactR { get; set; }
        public string Email { get; set; }
        public string AadharNo { get; set; }
        public string PANNo { get; set; }
        public string BankAcNo { get; set; }
        public string BankName { get; set; }
        public string AccType { get; set; }
        public string IFSC { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public string PensionStatus { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> PentionTypeID { get; set; }
        public Nullable<long> LicId { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string EmployeementType { get; set; }
        public Nullable<long> GradeId { get; set; }
        public Nullable<int> EmployeeType { get; set; }
        public Nullable<System.DateTime> HoldDate { get; set; }
        public string Remarks { get; set; }
        public string AnnuityMode { get; set; }
        public Nullable<int> Merged { get; set; }
        public Nullable<int> FromMerger { get; set; }
        public Nullable<System.DateTime> MDOJ { get; set; }
        public Nullable<System.DateTime> MDOL { get; set; }
        public Nullable<decimal> FrozenAmt { get; set; }
        public Nullable<decimal> FrozenPensionAmt { get; set; }
        public Nullable<int> Benefits { get; set; }
        public string Contribution { get; set; }
        public Nullable<decimal> RPensionAmt { get; set; }
        public Nullable<System.DateTime> SASettleDate { get; set; }
    }
}
