//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeChange
    {
        public int id { get; set; }
        public Nullable<int> Compnay_id { get; set; }
        public Nullable<int> EmpNo { get; set; }
        public Nullable<int> GradeChangeTo { get; set; }
        public Nullable<System.DateTime> EffDate { get; set; }
    }
}
