//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LifeCertificate
    {
        public int id { get; set; }
        public Nullable<int> InsCompId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string YearCode { get; set; }
        public string CertificateCopy { get; set; }
        public Nullable<System.DateTime> EffDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}
