//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomineeMaster
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Relation { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Addess { get; set; }
        public string Contact { get; set; }
        public string Mobile { get; set; }
        public string Adharnumber { get; set; }
        public string Pan { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string AccountNo { get; set; }
        public string IFSC { get; set; }
        public Nullable<long> CompId { get; set; }
        public Nullable<long> EmpId { get; set; }
    }
}
