//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMaster
    {
        public int RID { get; set; }
        public string Role { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
