//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAEmpDetail
    {
        public int SAOBID { get; set; }
        public string EmpNo { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public string Year { get; set; }
        public Nullable<int> SAID { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<System.DateTime> SASettalDate { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<int> UploadedBy { get; set; }
    }
}
