//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAInterest
    {
        public long ID { get; set; }
        public Nullable<long> CompID { get; set; }
        public Nullable<decimal> LiveEmpInt { get; set; }
        public Nullable<decimal> LeftEmpInt { get; set; }
        public string LiveEffYear { get; set; }
        public string LeftEffYear { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
