//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensionModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryMaster
    {
        public int SID { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> EA { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> SalaryMonth { get; set; }
        public string Year { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
    }
}
